flags: {}
extra-package-dbs: []
packages:
- '.'
system-ghc: false
extra-deps:
- HUnit-1.3.0.0
- QuickCheck-2.8.1
- ansi-terminal-0.6.2.3
- async-2.0.2
- hspec-2.2.1
- hspec-core-2.2.1
- hspec-discover-2.2.1
- hspec-expectations-0.7.2
- primitive-0.6.1.0
- quickcheck-io-0.1.2
- random-1.1
- setenv-0.1.1.3
- stm-2.4.4
- tf-random-0.5
resolver: ghc-7.10.3
