flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
system-ghc: false
extra-deps:
- HUnit-1.3.0.0
- HaTeX-3.16.2.0
- QuickCheck-2.8.1
- StateVar-1.1.0.1
- ansi-terminal-0.6.2.3
- async-2.0.2
- base-orphans-0.4.4
- bifunctors-5.1
- comonad-4.2.7.2
- contravariant-1.3.3
- distributive-0.4.4
- hashable-1.2.3.3
- hspec-2.2.1
- hspec-core-2.2.1
- hspec-discover-2.2.1
- hspec-expectations-0.7.2
- loop-0.3.0
- matrix-0.3.4.4
- mtl-2.2.1
- nats-1.1
- parsec-3.1.9
- primitive-0.6.1.0
- quickcheck-io-0.1.2
- random-1.1
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- setenv-0.1.1.3
- stm-2.4.4
- tagged-0.8.2
- text-1.2.1.3
- tf-random-0.5
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- vector-0.11.0.0
- void-0.7.1
- wl-pprint-extras-3.5.0.5
resolver: ghc-7.10.3
